services:
  server:
    build:
      context: server/
    ports:
      - "8000:8000"
    volumes:
      - "./server:/app"
    environment:
      DB_URL: mongodb://root:example@mongo:27017/
      MONGODB_DATABASE_NAME: cv_parser
      MONGODB_RESUMES_TABLE: resumes
  mongo:
    image: mongo
    restart: always
    command: mongod --quiet --logpath /dev/null 
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./data:/data/db"

    